# Generated by Django 5.1.6 on 2025-02-07 20:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=150, verbose_name='Nombres')),
                ('dni', models.CharField(max_length=10, unique=True, verbose_name='DNI')),
                ('date_joined', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de registro')),
                ('date_creation', models.DateField(auto_now=True, verbose_name='Fecha de creacion')),
                ('date_update', models.DateField(auto_now_add=True, verbose_name='Fecha de actualizacion')),
                ('age', models.PositiveIntegerField(default=0, verbose_name='Age')),
                ('salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Salario')),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatar/%Y/%m/%d', verbose_name='Imagen de la empresa')),
                ('cv', models.ImageField(blank=True, null=True, upload_to='cv/%Y/%m/%d', verbose_name='CV')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'db_table': 'empleado',
                'ordering': ['id'],
            },
        ),
    ]
